### ISSUE TITLE
Error in algo stack branching example

### ISSUE THREAD

**Issue by arisliang** [pmorissette/bt#314]
>Traceback (most recent call last):
  File "C:/btexamples/algos_example.py", line 26, in <module>
    s = bt.Strategy('strategy', branch_stack, ['spy', 'agg'])
  File "bt\core.py", line 2107, in bt.core.Strategy.__init__
TypeError: 'AlgoStack' object is not iterable

Above error when running [Branching and Control Flow example](https://pmorissette.github.io/bt/algos.html)

**Comment by samuel-cmcc** [comment]
When instantiating the Strategy, try passing the algos as a list (i.e. `s = bt.Strategy('strategy', [branch_stack], ['spy', 'agg'])` instead of `s = bt.Strategy('strategy', branch_stack, ['spy', 'agg'])`).

**Comment by Socvest** [comment]
Thanks @samuel-cmcc this worked!

**Comment by none2003** [comment]
Why this issue is still opening? Waiting for someone to fix the [Branching and Control Flow example](https://pmorissette.github.io/bt/algos.html)?
