### ISSUE TITLE
Proper way to build locally

### ISSUE THREAD

**Issue by npezolano** [pmorissette/bt#341]
What's the proper way to build this project locally to test changes?

If I run `python setup.py install` I get the following error on importing bt:

```
>>> import bt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/magic/anaconda3/envs/py39/lib/python3.9/site-packages/bt-0.2.9-py3.9-linux-x86_64.egg/bt/__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/magic/anaconda3/envs/py39/lib/python3.9/site-packages/bt-0.2.9-py3.9-linux-x86_64.egg/bt/algos.py", line 16, in <module>
ImportError: cannot import name 'Algo' from 'bt.core' (/home/magic/.cache/Python-Eggs/bt-0.2.9-py3.9-linux-x86_64.egg-tmp/bt/core.cpython-39-x86_64-linux-gnu.so)
```

I was able to get this working via the following two commands but I'm not sure this is what should be done:

```
python setup.py install --force
pip install .
```

**Comment by timkpaine** [comment]
https://github.com/pmorissette/bt/blob/master/.github/workflows/build.yml
