### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'month'

### ISSUE THREAD

**Issue by matlabat** [pmorissette/bt#47]
Hello Philippe,

i just discover your backtest framework and I would like to say bravo for all the work you've done.
However, when I try to launch it at home, I got this Stack Error:

Traceback (most recent call last):
  File "C:/Program Files (x86)/Projects/ForexBTEngine/BTmorissetteTest.py", line 13, in <module>
    res = bt.run(test)
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\bt\backtest.py", line 26, in run
    bkt.run()
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\bt\backtest.py", line 165, in run
    self.strategy.run()
  File "bt/core.py", line 1161, in bt.core.Strategy.run (bt/core.c:15301)
  File "bt/core.py", line 1106, in bt.core.AlgoStack.__call__ (bt/core.c:14703)
    else:
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\bt\algos.py", line 218, in __call__
    if now.month != self.last_date.month:
AttributeError: 'numpy.int64' object has no attribute 'month'

I'm on python 3.4 but I thought that I made all the necessary changes to make it work (in ffn and in bt)... Did I miss something? Any idea?

Thanks for everything philippe.

Mathieu

**Comment by matlabat** [comment]
PS: here's is the code I run:

import bt
import pandas as pd

data = pd.read_csv("E:\\test.csv") 
# this "test.csv" is exactly the "data = bt.get('spy,agg', start='2010-01-01')" 
# that I just exported with a "to_csv" pandas method

s = bt.Strategy('s1', [bt.algos.RunMonthly(),
                       bt.algos.SelectAll(),
                       bt.algos.WeighEqually(),
                       bt.algos.Rebalance()])

test = bt.Backtest(s, data)
res = bt.run(test)

**Comment by pmorissette** [comment]
Hey @matlabat,

Thanks for the kind words!

I think the dates are not being parsed on your ```pd.read_csv``` call. 

Try using the following:

```
data = pd.read_csv("E:\test.csv", index_col="Date", parse_dates=True)
```

Let me know if that works.

Cheers,
Phil
