### ISSUE TITLE
Sentiment Trading 

### ISSUE THREAD

**Issue by knlmathur** [pmorissette/bt#66]
Hi I am having an issue running this code, can anyone figure out what mistake I am making?
I am basically downloading the SPY and a sentiment dataset from Quandl and doing exactly what Phil did in the "SMA" tutorial. When I run the code I get lots of errors.

```
import bt
import Quandl
import pandas as pd

#Download the Sentiment Data
sent= Quandl.get("ISE/EQU_SI", transform="rdiff", start_date="2010-01-01")
sent=sent['2010':'2016']

#Download SPY data
data1=Quandl.get("GOOG/NYSE_SPY", start_date="2010-01-01")
data1=data1['2010':'2016']
data1=data1.dropna()
data1=pd.DataFrame({"price":data1['Close']},)

#Generate Weights
tw1=sent.copy(deep=True)
signal=tw1['Equities']
tw1[signal >= 0]=1.0
tw1[signal < 0]=-1.0
tw1=pd.DataFrame({"sent":tw1['Equities']},)


#Convert to monthly Data
data2=data1.copy(deep=True)
data2=data2.to_monthly()

tw2=tw1.copy(deep=True)
tw2=tw2.to_monthly()

#Run the Strategy
strad=bt.Strategy('strad',[bt.algos.WeighSpecified(tw2),bt.algos.Rebalance()])
t1=bt.Backtest(strad,data2)
res1=bt.run(t1)
res1.plot()

```

When I run this code, I get the following errors:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/bt/backtest.py", line 26, in run
    bkt.run()
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/bt/backtest.py", line 169, in run
    self.stats = self.strategy.prices.calc_perf_stats()
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/ffn/core.py", line 1005, in calc_perf_stats
    return PerformanceStats(obj)
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/ffn/core.py", line 85, in __init__
    self._update(self.prices)
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/ffn/core.py", line 107, in _update
    self._calculate(obj)
  File "/Applications/Anaconda_Python2.7/anaconda/lib/python2.7/site-packages/ffn/core.py", line 315, in _calculate
    self.yearly_vol)
ZeroDivisionError: float division by zero
>>> res1.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'res1' is not defined
```

**Comment by pmorissette** [comment]
Hey @knlmathur,

You should be using the ```WeighTarget``` algo (not ```WeighSpecified```). Also, your target weights (```tw1/tw2```) should have the same column names as your prices DataFrame (```tw2.columns = ['price']```).

Hope this helps,
Phil
